spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html,application/javascript
    min-response-size: 1024

logging:
  level:
    com.ecommerce: DEBUG

jwt:
  secret: ${JWT_SECRET:myVerySecureSecretKeyThatIsLongEnoughForJWTHMACSHA256AlgorithmForTest}
  expiration: 86400000

cors:
  allowedOrigins:
    - http://localhost:3000
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowedHeaders:
    - "*"
  allowCreds: true